#### PRODUCTOS #####

### Obtención de todos los productos - (Pueden acceder todos)
GET http://localhost:1234/productos

### Obtención de un producto específico (Pueden acceder todos)
GET http://localhost:1234/productos/producto/3/

### Modificar cantidad de stock de un producto (Tiene que ser nivel 2 y estar asignado a este producto el id_proveedor)
PATCH http://localhost:1234/productosStock/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoicmljRGVsbCIsIm5pdmVsIjoyLCJleHAiOjE2OTg5NjI3MzcxNTUsImlhdCI6MTY5ODk1MjczN30.pfyZumnRKWP91pe4LHqesuLOyAFbl7HDci_pn9kd2o4

{
    "stock": 500
}

###  Agregado de un producto nuevo (Solo Usuario 3 "Administrador") -- Se envia el id del proveedor correspondiente
POST http://localhost:1234/productosAgregar/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg4MjQyMjkwOTcsImlhdCI6MTY5ODgxNDIyOX0.ewzKWvzQsf-Dv2ewuiPmWwor0x0pa72NO4nOSJlcSd0

{

    "nombre": "Luz Led Philips",
    "precio": 400,
    "stock" : 1200
}

### 5) Borrado de un producto (Solo Usuario 3 "Administrador")
DELETE http://localhost:1234/productosBorrar/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg5NjY2OTI3MzgsImlhdCI6MTY5ODk1NjY5Mn0.cWDjp0JnGFxKDVC4K1Py11lk1nZpxmdMP78OMfFxdF8





#### TAREAS PARA ADM #### 

### Ver todos los Adm
GET http://localhost:1234/administradores/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg5NjcyODQ5OTUsImlhdCI6MTY5ODk1NzI4NH0.iRwKxBbvscI1mossKLe5nTp6G4dIbD4nLBrZrFYSwIU

### Ver todos los Clientes 
GET http://localhost:1234/todosClientes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg5NjcyODQ5OTUsImlhdCI6MTY5ODk1NzI4NH0.iRwKxBbvscI1mossKLe5nTp6G4dIbD4nLBrZrFYSwIU

### Ver todos los Proveedores 
GET http://localhost:1234/todosProveedores/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg5NjcyODQ5OTUsImlhdCI6MTY5ODk1NzI4NH0.iRwKxBbvscI1mossKLe5nTp6G4dIbD4nLBrZrFYSwIU

### Nuevo Proveedor
POST http://localhost:1234/nuevoProovedor/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg5NjcyODQ5OTUsImlhdCI6MTY5ODk1NzI4NH0.iRwKxBbvscI1mossKLe5nTp6G4dIbD4nLBrZrFYSwIU

{
    "nombre": " Mauricio Baysse",
    "usuario": "mbaysse",
    "password": "mbaysse2222"
}
### Borrar Proveedor por ID
DELETE http://localhost:1234/borrarProveedor/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg4MjE2ODk5OTQsImlhdCI6MTY5ODgxMTY5MH0.X4DZNoBKwjBfzAA0hGv1ftygl7pRIqXPbJR1PIHhmp8

### Borrar Cliente por ID
DELETE http://localhost:1234/borrarCliente/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg4MjE2ODk5OTQsImlhdCI6MTY5ODgxMTY5MH0.X4DZNoBKwjBfzAA0hGv1ftygl7pRIqXPbJR1PIHhmp8

### Ver un Cliente desde un id (Solo Administrador)
GET http://localhost:1234/usuarios/3/
Content-Type: application/json       
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg5NjcyODQ5OTUsImlhdCI6MTY5ODk1NzI4NH0.iRwKxBbvscI1mossKLe5nTp6G4dIbD4nLBrZrFYSwIU








#### CLIENTES #### 

### Crear un nuevo CLIENTE (Sin token, todos pueden generar un Usuario Cliente) 
POST http://localhost:1234/nuevoCliente
Content-Type: application/json

{
    "nombre": " Marta",
    "email": "marta@email.com",
    "usuario": "marta",
    "password": "clave567"
}

### Hacer compra producto y enviar a ventas  (acá se ingresa la cantidad deseada y el id del producto elegido)
POST http://localhost:1234/nuevaCompra/
Content-Type: application/json       
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibnJleSIsIm5pdmVsIjozLCJleHAiOjE2OTg5NjcyODQ5OTUsImlhdCI6MTY5ODk1NzI4NH0.iRwKxBbvscI1mossKLe5nTp6G4dIbD4nLBrZrFYSwIU


{
    "producto_id": 2,
    "cantidad": 5,
}



### 5) Actualización de un usuario, el body lleva solo el atributo a modificar (Solo Administrador)
PATCH http://localhost:1234/usuariosModificar/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZWR1TWVzc2kiLCJuaXZlbCI6MSwiZXhwIjoxNjk4NjA4MTc5MDk0LCJpYXQiOjE2OTg1OTgxNzl9.EeaIP94SwgY_VhsAcbehVJoogYQEisCuCZeQ7j4QHPM

{
    "edad": 35
}






#### ACCIONES DEL CARRITO #####

### 1) Crear un carrito  (Usuario)
POST http://localhost:1234/carritos/nuevo
Content-Type: application/json

{
     "id_carrito": 3,
     "id_producto": 0,
     "nombre": "",
     "precio": 0,
     "cantidad": 0  
}

# ### 2) Sumar producto al carrito desde un id (Usuario)
# PATCH http://localhost:1234/carrito/1/2
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoibmljb1JleSIsIm5pdmVsIjozLCJleHAiOjE2OTgxMTk5MjQyMjksImlhdCI6MTY5ODExNjMyNH0.vgMNsI7D587AjcEJGAgK3MS548b9prI4MnxD5mLx4OE

# {
   
# }







# ### 10)  obtener el total del stock actual de productos, la sumatoria de los precios individuales.
# GET http://localhost:1234/productos/total/














### GENERAR TOKEN
POST http://localhost:1234/auth
Content-Type: application/json 

    {
        "usuario" : "nrey",
        "password" :  "nrey123"
    }


